"""
app.py
Streamlit demo app for the Football Match Result Prediction project.

Run with:
    streamlit run app.py

Requires model.pkl to exist (generated by running train_model.py first).
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import shap
import matplotlib.pyplot as plt

st.set_page_config(
    page_title="Football Match Result Predictor",
    page_icon="⚽",
    layout="wide",
)

LABEL_MAP = {0: "Away Win", 1: "Draw", 2: "Home Win"}

ATTRIBUTE_INFO = {
    "buildUpPlaySpeed": "Tempo of build-up play (slow → fast)",
    "buildUpPlayDribbling": "Tendency to dribble in build-up",
    "buildUpPlayPassing": "Passing accuracy during build-up",
    "chanceCreationPassing": "Reliance on passing to create chances",
    "chanceCreationCrossing": "Frequency of crosses when attacking",
    "chanceCreationShooting": "Tendency to shoot when attacking",
    "defencePressure": "Pressing intensity when out of possession",
    "defenceAggression": "Aggression level in defensive duels",
    "defenceTeamWidth": "Width of the defensive shape",
}

BASE_ATTRS = list(ATTRIBUTE_INFO.keys())


@st.cache_resource
def load_model():
    try:
        bundle = joblib.load("model.pkl")
        return bundle["model"], bundle["features"]

    except Exception as e:
        st.error(f"ERROR LOADING MODEL: {e}")
        return None, None


def main():
    st.title("⚽ Football Match Result Predictor")
    st.markdown(
        "Predict football match outcomes using **team tactical attributes** "
        "and explain the prediction with **SHAP**."
    )

    model, features = load_model()

    if model is None:
        st.error(
            "⚠️ `model.pkl` not found. Please run `python train_model.py` "
            "first (after placing `database.sqlite` in the `data/` folder)."
        )
        st.stop()

    st.divider()
    col_home, col_away = st.columns(2)

    home_vals = {}
    away_vals = {}

    with col_home:
        st.subheader("🏠 Home Team Tactical Attributes")
        for attr in BASE_ATTRS:
            home_vals[attr] = st.slider(
                f"{attr}", 1, 100, 50, help=ATTRIBUTE_INFO[attr], key=f"home_{attr}"
            )

    with col_away:
        st.subheader("🚌 Away Team Tactical Attributes")
        for attr in BASE_ATTRS:
            away_vals[attr] = st.slider(
                f"{attr}", 1, 100, 50, help=ATTRIBUTE_INFO[attr], key=f"away_{attr}"
            )

    st.divider()

    if st.button("🔮 Predict Match Result", type="primary", use_container_width=True):
        input_dict = {}
        for attr in BASE_ATTRS:
            input_dict[f"home_{attr}"] = home_vals[attr]
            input_dict[f"away_{attr}"] = away_vals[attr]

        X_input = pd.DataFrame([input_dict])[features]

        proba = model.predict_proba(X_input)[0]
        pred_class = int(np.argmax(proba))

        st.subheader("📊 Prediction Result")
        result_cols = st.columns(3)
        for i, cls_name in LABEL_MAP.items():
            with result_cols[i]:
                st.metric(
                    cls_name,
                    f"{proba[i]*100:.1f}%",
                    delta="Predicted" if i == pred_class else None,
                )

        st.success(f"**Predicted Outcome: {LABEL_MAP[pred_class]}**")

        st.divider()
        st.subheader("🔍 Why did the model predict this? (SHAP Explanation)")

        with st.spinner("Computing SHAP values..."):
            explainer = shap.TreeExplainer(model)
            shap_values = explainer(X_input)

            fig, ax = plt.subplots(figsize=(8, 6))
            shap.plots.waterfall(shap_values[0, :, pred_class], show=False)
            st.pyplot(fig)

        st.caption(
            "This waterfall plot shows how each tactical attribute pushed the "
            "prediction from the model's baseline expectation toward the final "
            f"predicted outcome: **{LABEL_MAP[pred_class]}**."
        )

    st.divider()
    with st.expander("ℹ️ About this project"):
        st.markdown(
            """
            This app demonstrates the model from the research paper
            *"Analysis of Feature Importance in Football Match Result Prediction
            Using Explainable Machine Learning."*

            - **Model**: Random Forest (200 trees, max depth 10, balanced class weight)
            - **Dataset**: European Soccer Database (Kaggle) — 19,355 matches, 11 European leagues
            - **Explainability**: SHAP TreeExplainer
            - **Test Accuracy**: 43.09% | **Weighted F1-Score**: 0.43
            """
        )


if __name__ == "__main__":
    main()
